spring:
  mail:
    username: your-email@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    password: your-app-password
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-secret: 0XwCqt50eEfO1gBPFU4H1DrCYj2D0Acm
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-id: cfd3b7b6cfd05db50dd6c2cf188bc902
            scope: profile_nickname,profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '1234'
    username: root
    url: jdbc:mariadb://localhost:3306/tradeflatform
aws:
  s3:
    secret-key: ${AWS_S3_SECRET_KEY}
    access-key: ${AWS_S3_ACCESS_KEY}
    region: ap-southeast-2
    bucket: ${AWS_BUCKET_NAME}
jwt:
  token-validity-in-seconds: '86400'
  secret: your_jwt_secret_key
